# Misc module

import people
import verbs
import names 

from random import *
from util import *
		
class Events(WordList):
	def __init__(self):
		super().__init__(['Ash Wednesday',
		'Christmas Eve',
		'Easter Sunday',
		'Friday',
		'Halloween',
		'Highschool Graduation',
		'Homecoming',
		'Hump Day',
		'Independence Day',
		'International Women\'s Day',
		'Junior Prom',
		'Mardis Gras',
		'Mother\'s Day',
		'my anniversary',
		'my birthday',
		'my wedding day',
		'New Year\'s Eve',
		'Spring Break',
		'St. Patrick\'s Day',
		'Superbowl Sunday',
		'teacher planning day',
		'Valentine\'s Day'])
		
	def RemoveMy(self, sWord):
		return sWord.replace('my ','')
		
	def GetWord(self, bRemoveMy = False):
		sEvent = ""
		
		sEvent = super().GetWord()
			
		if bRemoveMy:
			sEvent = self.RemoveMy(sEvent)
			
		return sEvent
		
class Hashtags(WordList):
	def __init__(self):
		super().__init__(['50shades',
			'amwriting',
			'BDSM',
			#'bitcoin',
			#'blockchain',
			'bot',
			'botally'
			'botlife',
			'botlove',
			'eartg',
			'eartg',
			'erotica',
			'erotica',
			'fantasy',
			'fiftyshades',
			'filthy',
			#'litecoin',
			'lovestory',
			'lprtg',
			'lprtg',
			'mrbrtg',
			'naughty',
			'nsfw',
			'PleaseRT',
			'scifi',
			'romance',
			'smut',
			'sorrynotsorry',
			'ssrtg',
			'ssrtg',
			'taboo',
			'truelove',
			'twitterbot',
			'twitterbot',
			'wprtg'])
		
class BadGirlNames(NounAdjList):
	DefaultNoun = 'slut'
	DefaultAdj = 'little'
	
	NounList = ['hussy',
		'minx',
		'nympho',
		'skank',
		'slut',
		'slut',
		'slut',
		'tart',
		'tramp',
		'trollop',
		'whore',
		'whore']
		
	AdjList = ['brazen',
		'cheeky',
		'filthy',
		'little',
		'nasty',
		'outrageous',
		'saucy',
		'shameless',
		'wanton']
		
class SexyAdjs(WordList):
	def __init__(self):
		super().__init__(['dirty',
		'erotic',
		'filthy',
		'hot',
		'kinky',
		'naughty',
		'sexy',
		'sensual',
		'steamy',
		'taboo'])

class BookSellers(WordList):
	def __init__(self):
		super().__init__(['Apple Books',
			'Amazon',
			'B&N',
			'Kindle Unlimited',
			'Kobo',
			'Radish Fiction',
			'Smashwords',
			'WattPad'])
			
class BookGirlsBasic(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Bride',
			'Bride',
			'Bridesmaid',
			'Co-ed',
			'Girlfriend',
			'Housewife',
			'Intern',
			'Lady',
			'Lesbian',
			'Maid',
			'Maiden',
			'Momma',
			'Sisters',
			'Step-Daughter',
			'Submissive',
			'Teacher',
			'Wallflower',
			'Waitress',
			'Wife',
			'Woman'])
			
class BookGirls(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Airline Stewardess',
			'Amish Maiden',
			'Anal Virgin',
			'Babysitter',
			'Bikini Model',
			'Bimbo',
			'Blonde',
			'Brat',
			'BBW',
			'Call-Girl',
			'College Girl',
			'Concubine',
			'Dominatrix',
			'Escort',
			'Fashion Model',
			'Farmer\'s Daughter',
			'Flight Attendant',
			'Futa',
			'Governess',
			'Handmaiden',
			'Harem Girl',
			'Hotwife',
			'House Maid',
			'Flight Attendant',
			'French Maid',
			'Librarian',
			'Lingerie Model',
			'Masseuse',
			'Mature Woman',
			'MILF',
			'Milk Maid',
			'Nanny',
			'Nurse',
			'Older Woman',
			'Pastor\'s Wife',
			'Princess',
			'Princess',
			'Redhead',
			'Sex Surrogate',
			'Secretary',
			'Secretary',
			'Sex Slave',
			'Sex Witch',
			'Schoolgirl',
			'Single Mom',
			'Small-Town Girl',
			'Slut',
			'Submissive',
			'Supermodel',
			'Teacher',
			'Twin Sisters',
			'Virgin',
			'Wet Nurse',
			'Whore'])
			
class BookGirlAdjs(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Amish',
		'Anal',
		'Asian',
		'Bashful',
		'BBW',
		'Beautiful',
		'Bi-Curious',
		'Black',
		'Blonde',
		'Buxom',
		'Chaste',
		'Christian',
		'Conservative',
		'Country',
		'Curvy',
		'Divorced',
		'Ebony',
		'Fertile',
		'Gorgeous',
		'Harem',
		'High-Heeled',
		'Hot',
		'Hot',
		'Innocent',
		'Innocent',
		'Kept',
		'Kinky',
		'Lactating',
		'Leggy',
		'Lesbian',
		'Married',
		'Naked',
		'Naked',
		'Naughty',
		'Nubile',
		'Nude',
		'Nudist',
		'Nursing',
		'Petite',
		'Pregnant',
		'Sex',
		'Shy',
		'Single',
		'Small-Town',
		'Submissive',
		'Taboo',
		'Teen',
		'Teenage',
		'Virgin',
		'Virgin',
		'Virgin',
		'Young'])
		
class BookGirlCompAdjs(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['BBW',
		'Bimbo',
		'Call-Girl',
		'Co-ed',
		'Concubine',
		'Dominatrix',
		'Futa',
		'Hotwife',
		'Intern',
		'Lesbian',
		'MILF',
		'Redhead',
		'Servant',
		'Single Mom',
		'Submissive',
		'Supermodel',
		'Teen'])
		
class BookMastersBasic(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Alpha',
			'Boyfriend',
			'Dad',
			'Daddy',
			'Family Man',
			'Father-in-Law',
			'Gentleman',
			'Husband',
			'Preacher',
			'President',
			'Prince',
			'Roommate',
			'Step-Dad',
			'Widower'])

class BookMasters(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Alpha',
			'Alpha Wolf',
			'Astronaut',
			'Assassin',
			'Barbarian',
			'BBC',
			'Biker',
			'Billionaire',
			'Bitcoin Billionaire',
			'Bodyguard',
			'Boss',
			'Breeding Stud',
			'CEO',
			'Centaur',
			'Centaur',
			'Count',
			'Cop',
			'Cowboy',
			'Dad',
			'Daddy',
			'Daddy Dom',
			'Defensive Lineman',
			'Dildo Designer',
			'Dinosaur',
			'Doctor',
			'Dom',
			'Dominatrix',
			'Duke',
			'Duke',
			'Futanari',
			'Gangsta',
			'Gay-for-Pay Porn Star',
			'Gazillionaire',
			'Gentleman',
			'Goat Man',
			'Hitman',
			'Incubus',
			'Fire Fighter',
			'Jet Fighter Pilot',
			'King',
			'King',
			'King',
			'Knight',
			'Lesbian Cheerleader',
			'Lesbian Dominatrix',
			'Lesbian MILF',
			'Lipstick Lesbian',
			'Older Man',
			'Olympic Gold Medalist',
			'Outlaw',
			'Male Escort',
			'Male Stripper',
			'Man-o-taur',
			'Manor Lord',
			'Man-telope',
			'Man-ticore',
			'Marquis',
			'Mer-man',
			'MMA Fighter',
			'Millionaire',
			'Mob Boss',
			'Mountain Man',
			'Multi-Millionaire',
			'Navy Seal',
			'Pirate Captain',
			'Playboy Billionaire',
			'Pope',
			'Porn Star',
			'President',
			'Prime Minister',
			'Prince',
			'Prince',
			'Prince',
			'Professor',
			'Quarterback',
			'Rock Star',
			'Shah',
			'Sex Addict',
			'Sex Warlock',
			'Sheikh',
			'Sheriff',
			'Single Dad',
			'Sorcerer',
			'Spy',
			'Sultan',
			'Surfer',
			'Trillionaire',
			'Viking',
			'Uniporn',
			'Vampire',
			'Voyeur',
			'Werewolf'])
			
class BookMasterGangs(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Baby Daddies',
			'Bandits',
			'Barbarians',
			'Cops',
			'Cowboy',
			'Cowboys',
			'Football Team',
			'Gangstas',
			'Goat Men',
			'Lesbian Harem',
			'Mer-men',
			'Mountain Men',
			'Navy Seals',
			'Pirates',
			'Rock Band',
			'Seal Team Six',
			'S.W.A.T. Team',
			'Scottsmen',
			'Viking Hoard',
			'Vampire Coven',
			'Werewolf Pack'])
			
class BookMasterAdjs(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Alpha',
			'Australian',
			'Bad Boy',
			'Black',
			'BDSM',
			'Dominant',
			'Ebony',
			'French',
			'Handsome',
			'Highlander',
			'Horny',
			'Irish',
			'Italian',
			'Naked',
			'Norwegian',
			'Nudist',
			'Playboy',
			'Rebel',
			'Rock-Hard',
			'Savage',
			'Scottish',
			'Secret',
			'Sexy',
			'Shape-Shifting',
			'Shameless',
			'Silver Fox',
			'Space',
			'Spanish',
			'Stay-at-Home',
			'Visibly Erect',
			'Well-Hung',
			'Well-Endowed',
			'Wicked',
			'Widowed'])
			
class BookMasterCompAdjs(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Astronaut',
			'Bitcoin Billionaire',
			'Biker',
			'Billionaire',
			'Bodyguard',
			'Centaur',
			'Cowboy',
			'Defensive Lineman',
			'Dinosaur',
			'Fire Fighter',
			'Futanari',
			'Gazillionaire',
			'Goat Man',
			'Hitman',
			'Mer-man',
			'Millionaire',
			'MMA Fighter',
			'Mountain Man',
			'Multi-Millionaire',
			'Navy Seal',
			'Older Man',
			'Olympic Gold Medalist',
			'Outlaw',
			'Pirate',
			'Porn Star',
			'Rock Star',
			'Sex Addict',
			'Single Dad',
			'Stripper',
			'Surfer',
			'S.W.A.T. Team',
			'Trillionaire',
			'Viking',
			'Werewolf'])
			
class BookVerbsBy(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Anally Deflowered',
			'Annally Deflowered in Public',
			'Beaten',
			'Blackmailed',
			'Bound',
			'Bred',
			'Captured',
			'Claimed',
			'Claimed',
			'Claimed Hard',
			'Claimed in Public',
			'Conquered',
			'Charmed',
			'Cuckolded',
			'Deflowered',
			'Deflowered',
			'Deflowered in Public',
			'Dominated',
			'Enslaved',
			'Exposed in Public',
			'Forced',
			'Hotwifed',
			'Humiliated',
			'Hunted For Food',
			'Impregnated',
			'Kept',
			'Knocked Up',
			'Mastered',
			'Owned',
			'Pleasured',
			'Pleasured in Public',
			'Punished',
			'Punished in Public',
			'Ravished',
			'Seduced',
			'Sexually Harrassed At My Workplace',
			'Sold',
			'Sold',
			'Spanked',
			'Spanked in Public',
			'Shaved',
			'Stripped',
			'Stripped in Public',
			'Taken',
			'Taken',
			'Taken Hard',
			'Taken Hard in Public',
			'Taken in Public',
			'Tempted',
			'Trained',
			'Secretly Watched'])
			
class BookVerbsTo(WordList):
	WordHistoryQ = HistoryQ(3)
	
	def __init__(self):
		super().__init__(['Bred',
				'Bound',
				'Chained',
				'Engaged',
				'Enslaved',
				'Gifted',
				'Hotwifed',
				'Married',
				'Mated',
				'Pledged',
				'Sold'])
			
